
export enum ChartType {
    AnnotationChart = 'AnnotationChart',
    AreaChart = 'AreaChart',
    Bar = 'Bar',
    BarChart = 'BarChart',
    BubbleChart = 'BubbleChart',
    Calendar = 'Calendar',
    CandlestickChart = 'CandlestickChart',
    ColumnChart = 'ColumnChart',
    ComboChart = 'ComboChart',
    PieChart = 'PieChart',
    Gantt = 'Gantt',
    Gauge = 'Gauge',
    GeoChart = 'GeoChart',
    Histogram = 'Histogram',
    Line = 'Line',
    LineChart = 'LineChart',
    Map = 'Map',
    OrgChart = 'OrgChart',
    Sankey = 'Sankey',
    Scatter = 'Scatter',
    ScatterChart = 'ScatterChart',
    SteppedAreaChart = 'SteppedAreaChart',
    Table = 'Table',
    Timeline = 'Timeline',
    TreeMap = 'TreeMap',
    WordTree = 'wordtree'
  }
  

export const ChartPackages = {
    [ChartType.AnnotationChart]: 'annotationchart',
    [ChartType.AreaChart]: 'corechart',
    [ChartType.Bar]: 'bar',
    [ChartType.BarChart]: 'corechart',
    [ChartType.BubbleChart]: 'corechart',
    [ChartType.Calendar]: 'calendar',
    [ChartType.CandlestickChart]: 'corechart',
    [ChartType.ColumnChart]: 'corechart',
    [ChartType.ComboChart]: 'corechart',
    [ChartType.PieChart]: 'corechart',
    [ChartType.Gantt]: 'gantt',
    [ChartType.Gauge]: 'gauge',
    [ChartType.GeoChart]: 'geochart',
    [ChartType.Histogram]: 'corechart',
    [ChartType.Line]: 'line',
    [ChartType.LineChart]: 'corechart',
    [ChartType.Map]: 'map',
    [ChartType.OrgChart]: 'orgchart',
    [ChartType.Sankey]: 'sankey',
    [ChartType.Scatter]: 'scatter',
    [ChartType.ScatterChart]: 'corechart',
    [ChartType.SteppedAreaChart]: 'corechart',
    [ChartType.Table]: 'table',
    [ChartType.Timeline]: 'timeline',
    [ChartType.TreeMap]: 'treemap',
    [ChartType.WordTree]: 'wordtree'
  };

